config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'

  root 'dashboards#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save :downcase_email

  has_secure_password

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :email, :name, :surname, presence: true

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authenticatable
end

app/controllers/concerns/authenticatable.rb
# frozen_string_literal: true

module Authenticatable
  extend ActiveSupport::Concern

  included do
    before_action :current_user
    helper_method :current_user
  end

  def login(user)
    session[:current_user_id] = user.id
  end

  def logout
    reset_session
  end

  def redirect_authenticated
    redirect_to root_path if current_user
  end

  private

  def current_user
    @user ||= User.find_by(id: session[:current_user_id]) if session[:current_user_id]
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  before_action :authenticated?

  def index; end

  private

  def authenticated?
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :redirect_authenticated, only: %i[create new]

  def new; end

  def create
    @user = User.find_by(email: valid_params['email'].downcase)
    if @user&.authenticate(valid_params['password'])
      login @user
      redirect_to root_path, notice: 'Signed in.'
    else
      flash.now[:alert] = 'Incorrect email or password.'
      render :new, status: :unauthorized
    end
  end

  def destroy
    logout
    redirect_to '/login', notice: 'Logged out'
  end

  private

  def valid_params
    @valid_params ||= params.require('credentials').permit('email', 'password')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :redirect_authenticated, only: %i[create new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(valid_params)
    if @user.save
      redirect_to root_path, notice: 'User created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def valid_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/dashboards/index.html.erb
<h1>You are logged in as: <%= current_user.name %> </h1>

<%= link_to "Sign out", logout_path, data: { "turbo-method": :delete } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicAuthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user, url: sign_up_path do |form| %>
  <% if form.object.errors.any? %>
    <ul>
      <% form.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, required: true %>
  </div>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>
  <div>
    <%= form.label :surname %>
    <%= form.text_field :surname, required: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>
  <%= form.submit "Sign Up" %>
<% end %>